export interface TypewriterWord {
  text: string
  typingSpeed?: number
  deletingSpeed?: number
  pauseTime?: number
}

export const ensurePhrases: TypewriterWord[] = [
  { text: "clean water...", typingSpeed: 60, deletingSpeed: 30, pauseTime: 600 },
  { text: "natural capital...", typingSpeed: 70, deletingSpeed: 35, pauseTime: 800 },
  { text: "climate stability...", typingSpeed: 75, deletingSpeed: 37, pauseTime: 700 },
  { text: "clean air...", typingSpeed: 60, deletingSpeed: 30, pauseTime: 600 },
  { text: "biodiversity...", typingSpeed: 65, deletingSpeed: 32, pauseTime: 700 },
  { text: "healthy soil...", typingSpeed: 65, deletingSpeed: 32, pauseTime: 600 },
  { text: "wildfire protection...", typingSpeed: 75, deletingSpeed: 37, pauseTime: 700 },
  { text: "ecosystem services...", typingSpeed: 75, deletingSpeed: 37, pauseTime: 800 },
  { text: "resilience...", typingSpeed: 60, deletingSpeed: 30, pauseTime: 600 },
  { text: "well-being...", typingSpeed: 65, deletingSpeed: 32, pauseTime: 600 },
  { text: "coastal protection...", typingSpeed: 75, deletingSpeed: 37, pauseTime: 700 },
  { text: "health...", typingSpeed: 55, deletingSpeed: 28, pauseTime: 500 },
  { text: "impact...", typingSpeed: 55, deletingSpeed: 28, pauseTime: 500 },
  { text: "colorado river...", typingSpeed: 70, deletingSpeed: 35, pauseTime: 600 },
  { text: "my legacy...", typingSpeed: 60, deletingSpeed: 30, pauseTime: 600 },
  { text: "the amazon river...", typingSpeed: 65, deletingSpeed: 32, pauseTime: 600 },
  { text: "risk reduction...", typingSpeed: 70, deletingSpeed: 35, pauseTime: 700 },
  { text: "victoria falls...", typingSpeed: 75, deletingSpeed: 37, pauseTime: 700 },
  { text: "cenotes...", typingSpeed: 55, deletingSpeed: 28, pauseTime: 500 },
  { text: "water abundance...", typingSpeed: 70, deletingSpeed: 35, pauseTime: 600 },
  { text: "flood control...", typingSpeed: 65, deletingSpeed: 32, pauseTime: 600 },
  { text: "coral reefs...", typingSpeed: 60, deletingSpeed: 30, pauseTime: 600 },
  { text: "sea turtles...", typingSpeed: 65, deletingSpeed: 32, pauseTime: 600 },
  { text: "humpback whales...", typingSpeed: 70, deletingSpeed: 35, pauseTime: 700 },
  { text: "vaquita porpoise...", typingSpeed: 75, deletingSpeed: 37, pauseTime: 700 },
  { text: "monarch butterflies...", typingSpeed: 70, deletingSpeed: 35, pauseTime: 700 },
  { text: "koala bear...", typingSpeed: 65, deletingSpeed: 32, pauseTime: 600 },
  { text: "spirit bear...", typingSpeed: 60, deletingSpeed: 30, pauseTime: 600 },
  { text: "elk...", typingSpeed: 55, deletingSpeed: 28, pauseTime: 500 },
  { text: "salmon...", typingSpeed: 60, deletingSpeed: 30, pauseTime: 600 },
  { text: "amur leopard...", typingSpeed: 70, deletingSpeed: 35, pauseTime: 700 },
  { text: "carbon sequestration...", typingSpeed: 75, deletingSpeed: 37, pauseTime: 700 },
  { text: "sumatran tiger...", typingSpeed: 75, deletingSpeed: 37, pauseTime: 700 },
  { text: "iberian lynx...", typingSpeed: 70, deletingSpeed: 35, pauseTime: 700 },
  { text: "habitat...", typingSpeed: 60, deletingSpeed: 30, pauseTime: 600 },
  { text: "wetlands...", typingSpeed: 65, deletingSpeed: 32, pauseTime: 600 },
  { text: "grasslands...", typingSpeed: 70, deletingSpeed: 35, pauseTime: 700 },
  { text: "erosion control...", typingSpeed: 70, deletingSpeed: 35, pauseTime: 700 },
  { text: "fungi...", typingSpeed: 55, deletingSpeed: 28, pauseTime: 500 },
  { text: "mycelium...", typingSpeed: 65, deletingSpeed: 32, pauseTime: 600 },
  { text: "heat reduction...", typingSpeed: 70, deletingSpeed: 35, pauseTime: 700 },
  { text: "climate adaptation...", typingSpeed: 70, deletingSpeed: 35, pauseTime: 700 },
  { text: "adaptive capacity...", typingSpeed: 65, deletingSpeed: 32, pauseTime: 600 },
  { text: "mount thielsen...", typingSpeed: 70, deletingSpeed: 35, pauseTime: 700 },
  { text: "cascadia bioregion...", typingSpeed: 75, deletingSpeed: 37, pauseTime: 700 },
  { text: "open space...", typingSpeed: 60, deletingSpeed: 30, pauseTime: 600 },
  { text: "place...", typingSpeed: 55, deletingSpeed: 28, pauseTime: 500 },
  { text: "my town...", typingSpeed: 60, deletingSpeed: 30, pauseTime: 600 },
  { text: "flint mi...", typingSpeed: 65, deletingSpeed: 32, pauseTime: 600 },
  { text: "mumbai...", typingSpeed: 60, deletingSpeed: 30, pauseTime: 600 },
  { text: "sydney...", typingSpeed: 55, deletingSpeed: 28, pauseTime: 500 },
  { text: "cape town...", typingSpeed: 60, deletingSpeed: 30, pauseTime: 600 },
  { text: "buenos aires...", typingSpeed: 65, deletingSpeed: 32, pauseTime: 600 },
  { text: "los angeles...", typingSpeed: 70, deletingSpeed: 35, pauseTime: 700 },
  { text: "the congo river basin...", typingSpeed: 75, deletingSpeed: 37, pauseTime: 700 },
  { text: "lake creek...", typingSpeed: 65, deletingSpeed: 32, pauseTime: 600 },
  { text: "natural assets...", typingSpeed: 65, deletingSpeed: 32, pauseTime: 600 },
  { text: "green infra...", typingSpeed: 60, deletingSpeed: 30, pauseTime: 600 },
  { text: "pollination...", typingSpeed: 65, deletingSpeed: 32, pauseTime: 600 },
  { text: "my business...", typingSpeed: 65, deletingSpeed: 32, pauseTime: 600 },
  { text: "lake winnipausake...", typingSpeed: 80, deletingSpeed: 40, pauseTime: 700 },
  { text: "my portfolio...", typingSpeed: 70, deletingSpeed: 35, pauseTime: 700 },
  { text: "my investments...", typingSpeed: 75, deletingSpeed: 37, pauseTime: 700 },
  { text: "my health...", typingSpeed: 60, deletingSpeed: 30, pauseTime: 600 },
  { text: "happiness...", typingSpeed: 60, deletingSpeed: 30, pauseTime: 600 },
  { text: "ubi...", typingSpeed: 50, deletingSpeed: 25, pauseTime: 500 },
  { text: "living wages...", typingSpeed: 65, deletingSpeed: 32, pauseTime: 600 },
  { text: "my family...", typingSpeed: 60, deletingSpeed: 30, pauseTime: 600 },
  { text: "my groups work...", typingSpeed: 70, deletingSpeed: 35, pauseTime: 700 },
  { text: "my organization...", typingSpeed: 75, deletingSpeed: 37, pauseTime: 700 },
  { text: "my company...", typingSpeed: 65, deletingSpeed: 32, pauseTime: 600 },
  { text: "beauty...", typingSpeed: 55, deletingSpeed: 28, pauseTime: 500 },
  { text: "the earth...", typingSpeed: 65, deletingSpeed: 32, pauseTime: 600 }
] 