export const poolNameMappings: Record<string, { displayName: string; category: 'Ecosystems' | 'Core Benefits' }> = {
    'boreal-forests.ensurance': { displayName: 'Boreal Forests', category: 'Ecosystems' },
    'coastal-systems.ensurance': { displayName: 'Coastal Systems', category: 'Ecosystems' },
    'cultivated-developed.ensurance': { displayName: 'Cultivated & Developed', category: 'Ecosystems' },
    'deserts.ensurance': { displayName: 'Deserts', category: 'Ecosystems' },
    'grasslands.ensurance': { displayName: 'Grasslands', category: 'Ecosystems' },
    'inland-wetlands.ensurance': { displayName: 'Inland Wetlands', category: 'Ecosystems' },
    'polar-alpine.ensurance': { displayName: 'Polar & Alpine', category: 'Ecosystems' },
    'rivers-lakes.ensurance': { displayName: 'Rivers & Lakes', category: 'Ecosystems' },
    'rural-open-space.ensurance': { displayName: 'Rural Open Space', category: 'Ecosystems' },
    'shrublands.ensurance': { displayName: 'Shrublands', category: 'Ecosystems' },
    'subterranean.ensurance': { displayName: 'Subterranean', category: 'Ecosystems' },
    'temperate-forests.ensurance': { displayName: 'Temperate Forests', category: 'Ecosystems' },
    'tropical-forests.ensurance': { displayName: 'Tropical Forests', category: 'Ecosystems' },
    'urban-open-space.ensurance': { displayName: 'Urban Open Space', category: 'Ecosystems' },

    'aesthetic-sensory.ensurance': { displayName: 'Aesthetic & Sensory', category: 'Core Benefits' },
    'clean-air.ensurance': { displayName: 'Clean Air', category: 'Core Benefits' },
    'art-inspiration.ensurance': { displayName: 'Art & Inspiration', category: 'Core Benefits' },
    'clean-water.ensurance': { displayName: 'Clean Water', category: 'Core Benefits' },
    'climate-stability.ensurance': { displayName: 'Climate Stability', category: 'Core Benefits' },
    'energy.ensurance': { displayName: 'Energy', category: 'Core Benefits' },
    'erosion-control.ensurance': { displayName: 'Erosion Control', category: 'Core Benefits' },
    'existence-legacy.ensurance': { displayName: 'Existence & Legacy', category: 'Core Benefits' },
    'food.ensurance': { displayName: 'Food', category: 'Core Benefits' },
    'habitat.ensurance': { displayName: 'Habitat', category: 'Core Benefits' },
    'healthy-soils.ensurance': { displayName: 'Healthy Soils', category: 'Core Benefits' },
    'medicinal-genetic.ensurance': { displayName: 'Medicinal & Genetic', category: 'Core Benefits' },
    'pest-disease-control.ensurance': { displayName: 'Pest & Disease Control', category: 'Core Benefits' },
    'pollination.ensurance': { displayName: 'Pollination', category: 'Core Benefits' },
    'raw-materials.ensurance': { displayName: 'Raw Materials', category: 'Core Benefits' },
    'recreation-experiences.ensurance': { displayName: 'Recreation & Experiences', category: 'Core Benefits' },
    'research-learning.ensurance': { displayName: 'Research & Learning', category: 'Core Benefits' },
    'risk-resilience.ensurance': { displayName: 'Risk Resilience', category: 'Core Benefits' },
    'water-abundance.ensurance': { displayName: 'Water Abundance', category: 'Core Benefits' }
}; 