export interface ExposureData {
  source: string;
  target: string;
  value: number;
}

export const exposureData: ExposureData[] = [
  { source: 'Food & Agriculture', target: 'Raw Materials', value: 3 },
  { source: 'Food & Agriculture', target: 'Food', value: 3 },
  { source: 'Food & Agriculture', target: 'Energy', value: 2 },
  { source: 'Food & Agriculture', target: 'Water Abundance', value: 3 },
  { source: 'Food & Agriculture', target: 'Healthy Soils', value: 3 },
  { source: 'Food & Agriculture', target: 'Medicinal & Genetic', value: 3 },
  { source: 'Food & Agriculture', target: 'Climate Stability', value: 3 },
  { source: 'Food & Agriculture', target: 'Clean Air', value: 2 },
  { source: 'Food & Agriculture', target: 'Clean Water', value: 3 },
  { source: 'Food & Agriculture', target: 'Risk Resilience', value: 3 },
  { source: 'Food & Agriculture', target: 'Pollination', value: 3 },
  { source: 'Food & Agriculture', target: 'Erosion Control', value: 3 },
  { source: 'Food & Agriculture', target: 'Pest & Disease Control', value: 3 },
  { source: 'Food & Agriculture', target: 'Habitat', value: 2 },
  { source: 'Food & Agriculture', target: 'Recreation & Experiences', value: 3 },
  { source: 'Food & Agriculture', target: 'Research & Learning', value: 3 },
  { source: 'Food & Agriculture', target: 'Aesthetic & Sensory', value: 3 },
  { source: 'Food & Agriculture', target: 'Art & Inspiration', value: 3 },
  { source: 'Food & Agriculture', target: 'Existence & Legacy', value: 3 },
  { source: 'Manufacturing & Materials', target: 'Raw Materials', value: 3 },
  { source: 'Manufacturing & Materials', target: 'Food', value: 1 },
  { source: 'Manufacturing & Materials', target: 'Energy', value: 3 },
  { source: 'Manufacturing & Materials', target: 'Water Abundance', value: 2 },
  { source: 'Manufacturing & Materials', target: 'Healthy Soils', value: 1 },
  { source: 'Manufacturing & Materials', target: 'Medicinal & Genetic', value: 3 },
  { source: 'Manufacturing & Materials', target: 'Climate Stability', value: 1 },
  { source: 'Manufacturing & Materials', target: 'Clean Air', value: 1 },
  { source: 'Manufacturing & Materials', target: 'Clean Water', value: 3 },
  { source: 'Manufacturing & Materials', target: 'Risk Resilience', value: 2 },
  { source: 'Manufacturing & Materials', target: 'Pollination', value: 1 },
  { source: 'Manufacturing & Materials', target: 'Erosion Control', value: 2 },
  { source: 'Manufacturing & Materials', target: 'Pest & Disease Control', value: 1 },
  { source: 'Manufacturing & Materials', target: 'Habitat', value: 2 },
  { source: 'Manufacturing & Materials', target: 'Recreation & Experiences', value: 1 },
  { source: 'Manufacturing & Materials', target: 'Research & Learning', value: 3 },
  { source: 'Manufacturing & Materials', target: 'Aesthetic & Sensory', value: 1 },
  { source: 'Manufacturing & Materials', target: 'Art & Inspiration', value: 3 },
  { source: 'Manufacturing & Materials', target: 'Existence & Legacy', value: 2 },
  { source: 'Raw Materials', target: 'Rivers & Lakes', value: 2 },
  { source: 'Food', target: 'Rivers & Lakes', value: 3 },
  { source: 'Energy', target: 'Rivers & Lakes', value: 2 },
  { source: 'Water Abundance', target: 'Rivers & Lakes', value: 3 },
  { source: 'Healthy Soils', target: 'Rivers & Lakes', value: 2 },
  { source: 'Medicinal & Genetic', target: 'Rivers & Lakes', value: 2 },
  { source: 'Climate Stability', target: 'Rivers & Lakes', value: 2 },
  { source: 'Clean Air', target: 'Rivers & Lakes', value: 1 },
  { source: 'Clean Water', target: 'Rivers & Lakes', value: 3 },
  { source: 'Risk Resilience', target: 'Rivers & Lakes', value: 3 },
  { source: 'Pollination', target: 'Rivers & Lakes', value: 1 },
  { source: 'Erosion Control', target: 'Rivers & Lakes', value: 2 },
  { source: 'Pest & Disease Control', target: 'Rivers & Lakes', value: 2 },
  { source: 'Habitat', target: 'Rivers & Lakes', value: 3 },
  { source: 'Recreation & Experiences', target: 'Rivers & Lakes', value: 3 },
  { source: 'Research & Learning', target: 'Rivers & Lakes', value: 3 },
  { source: 'Aesthetic & Sensory', target: 'Rivers & Lakes', value: 3 },
  { source: 'Art & Inspiration', target: 'Rivers & Lakes', value: 3 },
  { source: 'Existence & Legacy', target: 'Rivers & Lakes', value: 3 },
  { source: 'Raw Materials', target: 'Tropical Forest', value: 3 },
  { source: 'Food', target: 'Tropical Forest', value: 3 },
  { source: 'Energy', target: 'Tropical Forest', value: 3 },
  { source: 'Water Abundance', target: 'Tropical Forest', value: 3 },
  { source: 'Healthy Soils', target: 'Tropical Forest', value: 3 },
  { source: 'Medicinal & Genetic', target: 'Tropical Forest', value: 3 },
  { source: 'Climate Stability', target: 'Tropical Forest', value: 3 },
  { source: 'Clean Air', target: 'Tropical Forest', value: 3 },
  { source: 'Clean Water', target: 'Tropical Forest', value: 3 },
  { source: 'Risk Resilience', target: 'Tropical Forest', value: 3 },
  { source: 'Pollination', target: 'Tropical Forest', value: 3 },
  { source: 'Erosion Control', target: 'Tropical Forest', value: 3 },
  { source: 'Pest & Disease Control', target: 'Tropical Forest', value: 3 },
  { source: 'Habitat', target: 'Tropical Forest', value: 3 },
  { source: 'Recreation & Experiences', target: 'Tropical Forest', value: 3 },
  { source: 'Research & Learning', target: 'Tropical Forest', value: 3 },
  { source: 'Aesthetic & Sensory', target: 'Tropical Forest', value: 3 },
  { source: 'Art & Inspiration', target: 'Tropical Forest', value: 3 },
  { source: 'Existence & Legacy', target: 'Tropical Forest', value: 3 },
  { source: 'Raw Materials', target: 'Temperate Forest', value: 3 },
  { source: 'Food', target: 'Temperate Forest', value: 2 },
  { source: 'Energy', target: 'Temperate Forest', value: 2 },
  { source: 'Water Abundance', target: 'Temperate Forest', value: 3 },
  { source: 'Healthy Soils', target: 'Temperate Forest', value: 3 },
  { source: 'Medicinal & Genetic', target: 'Temperate Forest', value: 3 },
  { source: 'Climate Stability', target: 'Temperate Forest', value: 3 },
  { source: 'Clean Air', target: 'Temperate Forest', value: 3 },
  { source: 'Clean Water', target: 'Temperate Forest', value: 3 },
  { source: 'Risk Resilience', target: 'Temperate Forest', value: 3 },
  { source: 'Pollination', target: 'Temperate Forest', value: 3 },
  { source: 'Erosion Control', target: 'Temperate Forest', value: 3 },
  { source: 'Pest & Disease Control', target: 'Temperate Forest', value: 2 },
  { source: 'Habitat', target: 'Temperate Forest', value: 3 },
  { source: 'Recreation & Experiences', target: 'Temperate Forest', value: 3 },
  { source: 'Research & Learning', target: 'Temperate Forest', value: 3 },
  { source: 'Aesthetic & Sensory', target: 'Temperate Forest', value: 3 },
  { source: 'Art & Inspiration', target: 'Temperate Forest', value: 3 },
  { source: 'Existence & Legacy', target: 'Temperate Forest', value: 3 },
  { source: 'Energy & Power', target: 'Raw Materials', value: 2 },
  { source: 'Energy & Power', target: 'Food', value: 1 },
  { source: 'Energy & Power', target: 'Energy', value: 3 },
  { source: 'Energy & Power', target: 'Water Abundance', value: 3 },
  { source: 'Energy & Power', target: 'Healthy Soils', value: 2 },
  { source: 'Energy & Power', target: 'Medicinal & Genetic', value: 1 },
  { source: 'Energy & Power', target: 'Climate Stability', value: 3 },
  { source: 'Energy & Power', target: 'Clean Air', value: 1 },
  { source: 'Energy & Power', target: 'Clean Water', value: 3 },
  { source: 'Energy & Power', target: 'Risk Resilience', value: 3 },
  { source: 'Energy & Power', target: 'Pollination', value: 1 },
  { source: 'Energy & Power', target: 'Erosion Control', value: 3 },
  { source: 'Energy & Power', target: 'Pest & Disease Control', value: 1 },
  { source: 'Energy & Power', target: 'Habitat', value: 2 },
  { source: 'Energy & Power', target: 'Recreation & Experiences', value: 2 },
  { source: 'Energy & Power', target: 'Research & Learning', value: 3 },
  { source: 'Energy & Power', target: 'Aesthetic & Sensory', value: 1 },
  { source: 'Energy & Power', target: 'Art & Inspiration', value: 1 },
  { source: 'Energy & Power', target: 'Existence & Legacy', value: 3 },
  { source: 'Infrastructure & Construction', target: 'Raw Materials', value: 1 },
  { source: 'Infrastructure & Construction', target: 'Food', value: 1 },
  { source: 'Infrastructure & Construction', target: 'Energy', value: 3 },
  { source: 'Infrastructure & Construction', target: 'Water Abundance', value: 2 },
  { source: 'Infrastructure & Construction', target: 'Healthy Soils', value: 2 },
  { source: 'Infrastructure & Construction', target: 'Medicinal & Genetic', value: 1 },
  { source: 'Infrastructure & Construction', target: 'Climate Stability', value: 2 },
  { source: 'Infrastructure & Construction', target: 'Clean Air', value: 2 },
  { source: 'Infrastructure & Construction', target: 'Clean Water', value: 2 },
  { source: 'Infrastructure & Construction', target: 'Risk Resilience', value: 2 },
  { source: 'Infrastructure & Construction', target: 'Pollination', value: 1 },
  { source: 'Infrastructure & Construction', target: 'Erosion Control', value: 3 },
  { source: 'Infrastructure & Construction', target: 'Pest & Disease Control', value: 1 },
  { source: 'Infrastructure & Construction', target: 'Habitat', value: 2 },
  { source: 'Infrastructure & Construction', target: 'Recreation & Experiences', value: 2 },
  { source: 'Infrastructure & Construction', target: 'Research & Learning', value: 2 },
  { source: 'Infrastructure & Construction', target: 'Aesthetic & Sensory', value: 2 },
  { source: 'Infrastructure & Construction', target: 'Art & Inspiration', value: 1 },
  { source: 'Infrastructure & Construction', target: 'Existence & Legacy', value: 3 },
  { source: 'Retail', target: 'Raw Materials', value: 3 },
  { source: 'Retail', target: 'Food', value: 3 },
  { source: 'Retail', target: 'Energy', value: 2 },
  { source: 'Retail', target: 'Water Abundance', value: 2 },
  { source: 'Retail', target: 'Healthy Soils', value: 2 },
  { source: 'Retail', target: 'Medicinal & Genetic', value: 2 },
  { source: 'Retail', target: 'Climate Stability', value: 1 },
  { source: 'Retail', target: 'Clean Air', value: 1 },
  { source: 'Retail', target: 'Clean Water', value: 2 },
  { source: 'Retail', target: 'Risk Resilience', value: 2 },
  { source: 'Retail', target: 'Pollination', value: 2 },
  { source: 'Retail', target: 'Erosion Control', value: 2 },
  { source: 'Retail', target: 'Pest & Disease Control', value: 1 },
  { source: 'Retail', target: 'Habitat', value: 1 },
  { source: 'Retail', target: 'Recreation & Experiences', value: 3 },
  { source: 'Retail', target: 'Research & Learning', value: 2 },
  { source: 'Retail', target: 'Aesthetic & Sensory', value: 3 },
  { source: 'Retail', target: 'Art & Inspiration', value: 2 },
  { source: 'Retail', target: 'Existence & Legacy', value: 3 },
  { source: 'Transportation & Logistics', target: 'Raw Materials', value: 3 },
  { source: 'Transportation & Logistics', target: 'Food', value: 1 },
  { source: 'Transportation & Logistics', target: 'Energy', value: 3 },
  { source: 'Transportation & Logistics', target: 'Water Abundance', value: 1 },
  { source: 'Transportation & Logistics', target: 'Healthy Soils', value: 1 },
  { source: 'Transportation & Logistics', target: 'Medicinal & Genetic', value: 1 },
  { source: 'Transportation & Logistics', target: 'Climate Stability', value: 2 },
  { source: 'Transportation & Logistics', target: 'Clean Air', value: 1 },
  { source: 'Transportation & Logistics', target: 'Clean Water', value: 2 },
  { source: 'Transportation & Logistics', target: 'Risk Resilience', value: 2 },
  { source: 'Transportation & Logistics', target: 'Pollination', value: 1 },
  { source: 'Transportation & Logistics', target: 'Erosion Control', value: 3 },
  { source: 'Transportation & Logistics', target: 'Pest & Disease Control', value: 1 },
  { source: 'Transportation & Logistics', target: 'Habitat', value: 1 },
  { source: 'Transportation & Logistics', target: 'Recreation & Experiences', value: 3 },
  { source: 'Transportation & Logistics', target: 'Research & Learning', value: 2 },
  { source: 'Transportation & Logistics', target: 'Aesthetic & Sensory', value: 3 },
  { source: 'Transportation & Logistics', target: 'Art & Inspiration', value: 1 },
  { source: 'Transportation & Logistics', target: 'Existence & Legacy', value: 2 },
  { source: 'Finance & Insurance', target: 'Raw Materials', value: 2 },
  { source: 'Finance & Insurance', target: 'Food', value: 3 },
  { source: 'Finance & Insurance', target: 'Energy', value: 3 },
  { source: 'Finance & Insurance', target: 'Water Abundance', value: 3 },
  { source: 'Finance & Insurance', target: 'Healthy Soils', value: 2 },
  { source: 'Finance & Insurance', target: 'Medicinal & Genetic', value: 2 },
  { source: 'Finance & Insurance', target: 'Climate Stability', value: 3 },
  { source: 'Finance & Insurance', target: 'Clean Air', value: 3 },
  { source: 'Finance & Insurance', target: 'Clean Water', value: 3 },
  { source: 'Finance & Insurance', target: 'Risk Resilience', value: 3 },
  { source: 'Finance & Insurance', target: 'Pollination', value: 3 },
  { source: 'Finance & Insurance', target: 'Erosion Control', value: 3 },
  { source: 'Finance & Insurance', target: 'Pest & Disease Control', value: 3 },
  { source: 'Finance & Insurance', target: 'Habitat', value: 3 },
  { source: 'Finance & Insurance', target: 'Recreation & Experiences', value: 2 },
  { source: 'Finance & Insurance', target: 'Research & Learning', value: 3 },
  { source: 'Finance & Insurance', target: 'Aesthetic & Sensory', value: 2 },
  { source: 'Finance & Insurance', target: 'Art & Inspiration', value: 1 },
  { source: 'Finance & Insurance', target: 'Existence & Legacy', value: 3 },
  { source: 'Raw Materials', target: 'Boreal Forest', value: 3 },
  { source: 'Food', target: 'Boreal Forest', value: 1 },
  { source: 'Energy', target: 'Boreal Forest', value: 3 },
  { source: 'Water Abundance', target: 'Boreal Forest', value: 3 },
  { source: 'Healthy Soils', target: 'Boreal Forest', value: 2 },
  { source: 'Medicinal & Genetic', target: 'Boreal Forest', value: 2 },
  { source: 'Climate Stability', target: 'Boreal Forest', value: 3 },
  { source: 'Clean Air', target: 'Boreal Forest', value: 3 },
  { source: 'Clean Water', target: 'Boreal Forest', value: 3 },
  { source: 'Risk Resilience', target: 'Boreal Forest', value: 2 },
  { source: 'Pollination', target: 'Boreal Forest', value: 1 },
  { source: 'Erosion Control', target: 'Boreal Forest', value: 2 },
  { source: 'Pest & Disease Control', target: 'Boreal Forest', value: 1 },
  { source: 'Habitat', target: 'Boreal Forest', value: 3 },
  { source: 'Recreation & Experiences', target: 'Boreal Forest', value: 2 },
  { source: 'Research & Learning', target: 'Boreal Forest', value: 3 },
  { source: 'Aesthetic & Sensory', target: 'Boreal Forest', value: 3 },
  { source: 'Art & Inspiration', target: 'Boreal Forest', value: 3 },
  { source: 'Existence & Legacy', target: 'Boreal Forest', value: 3 },
  { source: 'Raw Materials', target: 'Coastal Systems', value: 3 },
  { source: 'Food', target: 'Coastal Systems', value: 3 },
  { source: 'Energy', target: 'Coastal Systems', value: 2 },
  { source: 'Water Abundance', target: 'Coastal Systems', value: 2 },
  { source: 'Healthy Soils', target: 'Coastal Systems', value: 2 },
  { source: 'Medicinal & Genetic', target: 'Coastal Systems', value: 2 },
  { source: 'Climate Stability', target: 'Coastal Systems', value: 3 },
  { source: 'Clean Air', target: 'Coastal Systems', value: 2 },
  { source: 'Clean Water', target: 'Coastal Systems', value: 3 },
  { source: 'Risk Resilience', target: 'Coastal Systems', value: 3 },
  { source: 'Pollination', target: 'Coastal Systems', value: 1 },
  { source: 'Erosion Control', target: 'Coastal Systems', value: 3 },
  { source: 'Pest & Disease Control', target: 'Coastal Systems', value: 2 },
  { source: 'Habitat', target: 'Coastal Systems', value: 3 },
  { source: 'Recreation & Experiences', target: 'Coastal Systems', value: 3 },
  { source: 'Research & Learning', target: 'Coastal Systems', value: 3 },
  { source: 'Aesthetic & Sensory', target: 'Coastal Systems', value: 3 },
  { source: 'Art & Inspiration', target: 'Coastal Systems', value: 3 },
  { source: 'Existence & Legacy', target: 'Coastal Systems', value: 3 },
  { source: 'Raw Materials', target: 'Inland Wetlands', value: 2 },
  { source: 'Food', target: 'Inland Wetlands', value: 2 },
  { source: 'Energy', target: 'Inland Wetlands', value: 2 },
  { source: 'Water Abundance', target: 'Inland Wetlands', value: 3 },
  { source: 'Healthy Soils', target: 'Inland Wetlands', value: 3 },
  { source: 'Medicinal & Genetic', target: 'Inland Wetlands', value: 2 },
  { source: 'Climate Stability', target: 'Inland Wetlands', value: 3 },
  { source: 'Clean Air', target: 'Inland Wetlands', value: 2 },
  { source: 'Clean Water', target: 'Inland Wetlands', value: 3 },
  { source: 'Risk Resilience', target: 'Inland Wetlands', value: 3 },
  { source: 'Pollination', target: 'Inland Wetlands', value: 1 },
  { source: 'Erosion Control', target: 'Inland Wetlands', value: 3 },
  { source: 'Pest & Disease Control', target: 'Inland Wetlands', value: 2 },
  { source: 'Habitat', target: 'Inland Wetlands', value: 3 },
  { source: 'Recreation & Experiences', target: 'Inland Wetlands', value: 3 },
  { source: 'Research & Learning', target: 'Inland Wetlands', value: 3 },
  { source: 'Aesthetic & Sensory', target: 'Inland Wetlands', value: 3 },
  { source: 'Art & Inspiration', target: 'Inland Wetlands', value: 3 },
  { source: 'Existence & Legacy', target: 'Inland Wetlands', value: 3 },
  { source: 'Raw Materials', target: 'Cultivated & Developed', value: 3 },
  { source: 'Food', target: 'Cultivated & Developed', value: 3 },
  { source: 'Energy', target: 'Cultivated & Developed', value: 2 },
  { source: 'Water Abundance', target: 'Cultivated & Developed', value: 1 },
  { source: 'Healthy Soils', target: 'Cultivated & Developed', value: 2 },
  { source: 'Medicinal & Genetic', target: 'Cultivated & Developed', value: 2 },
  { source: 'Climate Stability', target: 'Cultivated & Developed', value: 1 },
  { source: 'Clean Air', target: 'Cultivated & Developed', value: 1 },
  { source: 'Clean Water', target: 'Cultivated & Developed', value: 1 },
  { source: 'Risk Resilience', target: 'Cultivated & Developed', value: 1 },
  { source: 'Pollination', target: 'Cultivated & Developed', value: 2 },
  { source: 'Erosion Control', target: 'Cultivated & Developed', value: 1 },
  { source: 'Pest & Disease Control', target: 'Cultivated & Developed', value: 2 },
  { source: 'Habitat', target: 'Cultivated & Developed', value: 1 },
  { source: 'Recreation & Experiences', target: 'Cultivated & Developed', value: 3 },
  { source: 'Research & Learning', target: 'Cultivated & Developed', value: 3 },
  { source: 'Aesthetic & Sensory', target: 'Cultivated & Developed', value: 3 },
  { source: 'Art & Inspiration', target: 'Cultivated & Developed', value: 3 },
  { source: 'Existence & Legacy', target: 'Cultivated & Developed', value: 3 },
  { source: 'Raw Materials', target: 'Urban Open Space', value: 1 },
  { source: 'Food', target: 'Urban Open Space', value: 1 },
  { source: 'Energy', target: 'Urban Open Space', value: 1 },
  { source: 'Water Abundance', target: 'Urban Open Space', value: 1 },
  { source: 'Healthy Soils', target: 'Urban Open Space', value: 1 },
  { source: 'Medicinal & Genetic', target: 'Urban Open Space', value: 1 },
  { source: 'Climate Stability', target: 'Urban Open Space', value: 2 },
  { source: 'Clean Air', target: 'Urban Open Space', value: 3 },
  { source: 'Clean Water', target: 'Urban Open Space', value: 2 },
  { source: 'Risk Resilience', target: 'Urban Open Space', value: 2 },
  { source: 'Pollination', target: 'Urban Open Space', value: 2 },
  { source: 'Erosion Control', target: 'Urban Open Space', value: 1 },
  { source: 'Pest & Disease Control', target: 'Urban Open Space', value: 2 },
  { source: 'Habitat', target: 'Urban Open Space', value: 2 },
  { source: 'Recreation & Experiences', target: 'Urban Open Space', value: 3 },
  { source: 'Research & Learning', target: 'Urban Open Space', value: 3 },
  { source: 'Aesthetic & Sensory', target: 'Urban Open Space', value: 3 },
  { source: 'Art & Inspiration', target: 'Urban Open Space', value: 3 },
  { source: 'Existence & Legacy', target: 'Urban Open Space', value: 3 },
  { source: 'Raw Materials', target: 'Rural Open Space', value: 2 },
  { source: 'Food', target: 'Rural Open Space', value: 2 },
  { source: 'Energy', target: 'Rural Open Space', value: 2 },
  { source: 'Water Abundance', target: 'Rural Open Space', value: 2 },
  { source: 'Healthy Soils', target: 'Rural Open Space', value: 3 },
  { source: 'Medicinal & Genetic', target: 'Rural Open Space', value: 2 },
  { source: 'Climate Stability', target: 'Rural Open Space', value: 2 },
  { source: 'Clean Air', target: 'Rural Open Space', value: 2 },
  { source: 'Clean Water', target: 'Rural Open Space', value: 3 },
  { source: 'Risk Resilience', target: 'Rural Open Space', value: 3 },
  { source: 'Pollination', target: 'Rural Open Space', value: 3 },
  { source: 'Erosion Control', target: 'Rural Open Space', value: 3 },
  { source: 'Pest & Disease Control', target: 'Rural Open Space', value: 2 },
  { source: 'Habitat', target: 'Rural Open Space', value: 3 },
  { source: 'Recreation & Experiences', target: 'Rural Open Space', value: 3 },
  { source: 'Research & Learning', target: 'Rural Open Space', value: 3 },
  { source: 'Aesthetic & Sensory', target: 'Rural Open Space', value: 3 },
  { source: 'Art & Inspiration', target: 'Rural Open Space', value: 3 },
  { source: 'Existence & Legacy', target: 'Rural Open Space', value: 3 },
  { source: 'Raw Materials', target: 'Marine Systems', value: 3 },
  { source: 'Food', target: 'Marine Systems', value: 3 },
  { source: 'Energy', target: 'Marine Systems', value: 3 },
  { source: 'Water Abundance', target: 'Marine Systems', value: 3 },
  { source: 'Healthy Soils', target: 'Marine Systems', value: 1 },
  { source: 'Medicinal & Genetic', target: 'Marine Systems', value: 3 },
  { source: 'Climate Stability', target: 'Marine Systems', value: 3 },
  { source: 'Clean Air', target: 'Marine Systems', value: 2 },
  { source: 'Clean Water', target: 'Marine Systems', value: 3 },
  { source: 'Risk Resilience', target: 'Marine Systems', value: 3 },
  { source: 'Pollination', target: 'Marine Systems', value: 1 },
  { source: 'Erosion Control', target: 'Marine Systems', value: 2 },
  { source: 'Pest & Disease Control', target: 'Marine Systems', value: 2 },
  { source: 'Habitat', target: 'Marine Systems', value: 3 },
  { source: 'Recreation & Experiences', target: 'Marine Systems', value: 3 },
  { source: 'Research & Learning', target: 'Marine Systems', value: 3 },
  { source: 'Aesthetic & Sensory', target: 'Marine Systems', value: 3 },
  { source: 'Art & Inspiration', target: 'Marine Systems', value: 3 },
  { source: 'Existence & Legacy', target: 'Marine Systems', value: 3 },
  { source: 'Raw Materials', target: 'Grasslands', value: 2 },
  { source: 'Food', target: 'Grasslands', value: 3 },
  { source: 'Energy', target: 'Grasslands', value: 2 },
  { source: 'Water Abundance', target: 'Grasslands', value: 2 },
  { source: 'Healthy Soils', target: 'Grasslands', value: 3 },
  { source: 'Medicinal & Genetic', target: 'Grasslands', value: 2 },
  { source: 'Climate Stability', target: 'Grasslands', value: 3 },
  { source: 'Clean Air', target: 'Grasslands', value: 2 },
  { source: 'Clean Water', target: 'Grasslands', value: 2 },
  { source: 'Risk Resilience', target: 'Grasslands', value: 2 },
  { source: 'Pollination', target: 'Grasslands', value: 3 },
  { source: 'Erosion Control', target: 'Grasslands', value: 3 },
  { source: 'Pest & Disease Control', target: 'Grasslands', value: 2 },
  { source: 'Habitat', target: 'Grasslands', value: 3 },
  { source: 'Recreation & Experiences', target: 'Grasslands', value: 3 },
  { source: 'Research & Learning', target: 'Grasslands', value: 2 },
  { source: 'Aesthetic & Sensory', target: 'Grasslands', value: 3 },
  { source: 'Art & Inspiration', target: 'Grasslands', value: 3 },
  { source: 'Existence & Legacy', target: 'Grasslands', value: 3 },
  { source: 'Raw Materials', target: 'Shrublands', value: 2 },
  { source: 'Food', target: 'Shrublands', value: 1 },
  { source: 'Energy', target: 'Shrublands', value: 1 },
  { source: 'Water Abundance', target: 'Shrublands', value: 1 },
  { source: 'Healthy Soils', target: 'Shrublands', value: 1 },
  { source: 'Medicinal & Genetic', target: 'Shrublands', value: 2 },
  { source: 'Climate Stability', target: 'Shrublands', value: 2 },
  { source: 'Clean Air', target: 'Shrublands', value: 1 },
  { source: 'Clean Water', target: 'Shrublands', value: 1 },
  { source: 'Risk Resilience', target: 'Shrublands', value: 2 },
  { source: 'Pollination', target: 'Shrublands', value: 2 },
  { source: 'Erosion Control', target: 'Shrublands', value: 2 },
  { source: 'Pest & Disease Control', target: 'Shrublands', value: 1 },
  { source: 'Habitat', target: 'Shrublands', value: 3 },
  { source: 'Recreation & Experiences', target: 'Shrublands', value: 2 },
  { source: 'Research & Learning', target: 'Shrublands', value: 2 },
  { source: 'Aesthetic & Sensory', target: 'Shrublands', value: 3 },
  { source: 'Art & Inspiration', target: 'Shrublands', value: 3 },
  { source: 'Existence & Legacy', target: 'Shrublands', value: 3 },
  { source: 'Raw Materials', target: 'Polar & Alpine', value: 1 },
  { source: 'Food', target: 'Polar & Alpine', value: 1 },
  { source: 'Energy', target: 'Polar & Alpine', value: 2 },
  { source: 'Water Abundance', target: 'Polar & Alpine', value: 3 },
  { source: 'Healthy Soils', target: 'Polar & Alpine', value: 1 },
  { source: 'Medicinal & Genetic', target: 'Polar & Alpine', value: 2 },
  { source: 'Climate Stability', target: 'Polar & Alpine', value: 3 },
  { source: 'Clean Air', target: 'Polar & Alpine', value: 3 },
  { source: 'Clean Water', target: 'Polar & Alpine', value: 3 },
  { source: 'Risk Resilience', target: 'Polar & Alpine', value: 2 },
  { source: 'Pollination', target: 'Polar & Alpine', value: 1 },
  { source: 'Erosion Control', target: 'Polar & Alpine', value: 1 },
  { source: 'Pest & Disease Control', target: 'Polar & Alpine', value: 1 },
  { source: 'Habitat', target: 'Polar & Alpine', value: 3 },
  { source: 'Recreation & Experiences', target: 'Polar & Alpine', value: 2 },
  { source: 'Research & Learning', target: 'Polar & Alpine', value: 3 },
  { source: 'Aesthetic & Sensory', target: 'Polar & Alpine', value: 3 },
  { source: 'Art & Inspiration', target: 'Polar & Alpine', value: 3 },
  { source: 'Existence & Legacy', target: 'Polar & Alpine', value: 3 },
  { source: 'Raw Materials', target: 'Desert', value: 2 },
  { source: 'Food', target: 'Desert', value: 1 },
  { source: 'Energy', target: 'Desert', value: 3 },
  { source: 'Water Abundance', target: 'Desert', value: 1 },
  { source: 'Healthy Soils', target: 'Desert', value: 1 },
  { source: 'Medicinal & Genetic', target: 'Desert', value: 2 },
  { source: 'Climate Stability', target: 'Desert', value: 1 },
  { source: 'Clean Air', target: 'Desert', value: 1 },
  { source: 'Clean Water', target: 'Desert', value: 1 },
  { source: 'Risk Resilience', target: 'Desert', value: 1 },
  { source: 'Pollination', target: 'Desert', value: 1 },
  { source: 'Erosion Control', target: 'Desert', value: 1 },
  { source: 'Pest & Disease Control', target: 'Desert', value: 1 },
  { source: 'Habitat', target: 'Desert', value: 2 },
  { source: 'Recreation & Experiences', target: 'Desert', value: 2 },
  { source: 'Research & Learning', target: 'Desert', value: 3 },
  { source: 'Aesthetic & Sensory', target: 'Desert', value: 3 },
  { source: 'Art & Inspiration', target: 'Desert', value: 3 },
  { source: 'Existence & Legacy', target: 'Desert', value: 3 },
  { source: 'Raw Materials', target: 'Subterranean', value: 3 },
  { source: 'Food', target: 'Subterranean', value: 1 },
  { source: 'Energy', target: 'Subterranean', value: 3 },
  { source: 'Water Abundance', target: 'Subterranean', value: 3 },
  { source: 'Healthy Soils', target: 'Subterranean', value: 1 },
  { source: 'Medicinal & Genetic', target: 'Subterranean', value: 2 },
  { source: 'Climate Stability', target: 'Subterranean', value: 2 },
  { source: 'Clean Air', target: 'Subterranean', value: 1 },
  { source: 'Clean Water', target: 'Subterranean', value: 3 },
  { source: 'Risk Resilience', target: 'Subterranean', value: 2 },
  { source: 'Erosion Control', target: 'Subterranean', value: 1 },
  { source: 'Pest & Disease Control', target: 'Subterranean', value: 1 },
  { source: 'Habitat', target: 'Subterranean', value: 2 },
  { source: 'Recreation & Experiences', target: 'Subterranean', value: 2 },
  { source: 'Research & Learning', target: 'Subterranean', value: 3 },
  { source: 'Aesthetic & Sensory', target: 'Subterranean', value: 2 },
  { source: 'Art & Inspiration', target: 'Subterranean', value: 2 },
  { source: 'Existence & Legacy', target: 'Subterranean', value: 2 }
]; 